"""initial_schema

Revision ID: 3164506c2c1c
Revises: 
Create Date: 2026-02-04 09:50:14.440700

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3164506c2c1c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('decision_traces',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('request_id', sa.String(length=255), nullable=False),
    sa.Column('orchestrator_name', sa.String(length=100), nullable=False),
    sa.Column('trace_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_decision_traces_created_at'), 'decision_traces', ['created_at'], unique=False)
    op.create_index(op.f('ix_decision_traces_id'), 'decision_traces', ['id'], unique=False)
    op.create_index(op.f('ix_decision_traces_orchestrator_name'), 'decision_traces', ['orchestrator_name'], unique=False)
    op.create_index(op.f('ix_decision_traces_request_id'), 'decision_traces', ['request_id'], unique=False)
    op.create_table('idempotency_keys',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('request_id', sa.String(length=255), nullable=False),
    sa.Column('orchestrator_name', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='request_status'), nullable=False),
    sa.Column('request_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('response_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('error_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('result_resource_type', sa.String(length=50), nullable=True),
    sa.Column('result_resource_id', sa.UUID(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_idempotency_keys_created_at'), 'idempotency_keys', ['created_at'], unique=False)
    op.create_index(op.f('ix_idempotency_keys_expires_at'), 'idempotency_keys', ['expires_at'], unique=False)
    op.create_index(op.f('ix_idempotency_keys_id'), 'idempotency_keys', ['id'], unique=False)
    op.create_index(op.f('ix_idempotency_keys_orchestrator_name'), 'idempotency_keys', ['orchestrator_name'], unique=False)
    op.create_index(op.f('ix_idempotency_keys_request_id'), 'idempotency_keys', ['request_id'], unique=True)
    op.create_index(op.f('ix_idempotency_keys_result_resource_id'), 'idempotency_keys', ['result_resource_id'], unique=False)
    op.create_index(op.f('ix_idempotency_keys_status'), 'idempotency_keys', ['status'], unique=False)
    op.create_index(op.f('ix_idempotency_keys_user_id'), 'idempotency_keys', ['user_id'], unique=False)
    op.create_table('opportunities_catalog',
    sa.Column('opportunity_id', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('opportunity_type', sa.String(length=50), nullable=False),
    sa.Column('disciplines', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('eligible_stages', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('deadline', sa.Date(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('keywords', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('funding_amount', sa.Float(), nullable=True),
    sa.Column('prestige_level', sa.String(length=20), nullable=True),
    sa.Column('geographic_scope', sa.String(length=50), nullable=True),
    sa.Column('source_url', sa.String(), nullable=True),
    sa.Column('organization', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('requires_subscription', sa.Boolean(), nullable=False),
    sa.Column('subscription_tier', sa.String(length=50), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_opportunities_deadline_active', 'opportunities_catalog', ['deadline', 'is_active'], unique=False)
    op.create_index('idx_opportunities_type_active', 'opportunities_catalog', ['opportunity_type', 'is_active'], unique=False)
    op.create_index(op.f('ix_opportunities_catalog_deadline'), 'opportunities_catalog', ['deadline'], unique=False)
    op.create_index(op.f('ix_opportunities_catalog_is_active'), 'opportunities_catalog', ['is_active'], unique=False)
    op.create_index(op.f('ix_opportunities_catalog_opportunity_id'), 'opportunities_catalog', ['opportunity_id'], unique=True)
    op.create_index(op.f('ix_opportunities_catalog_opportunity_type'), 'opportunities_catalog', ['opportunity_type'], unique=False)
    op.create_table('questionnaire_versions',
    sa.Column('version_number', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('schema_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deprecated', sa.Boolean(), nullable=False),
    sa.Column('total_questions', sa.Integer(), nullable=False),
    sa.Column('total_sections', sa.Integer(), nullable=False),
    sa.Column('release_notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_questionnaire_versions_version_number'), 'questionnaire_versions', ['version_number'], unique=True)
    op.create_table('users',
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('institution', sa.String(), nullable=True),
    sa.Column('field_of_study', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('analytics_snapshots',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('timeline_version', sa.String(length=50), nullable=False),
    sa.Column('summary_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analytics_snapshots_timeline_version'), 'analytics_snapshots', ['timeline_version'], unique=False)
    op.create_index(op.f('ix_analytics_snapshots_user_id'), 'analytics_snapshots', ['user_id'], unique=False)
    op.create_table('document_artifacts',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('file_type', sa.String(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('document_type', sa.String(), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('document_text', sa.Text(), nullable=True),
    sa.Column('word_count', sa.Integer(), nullable=True),
    sa.Column('detected_language', sa.String(length=10), nullable=True),
    sa.Column('section_map_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('document_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_artifacts_user_id'), 'document_artifacts', ['user_id'], unique=False)
    op.create_table('evidence_bundles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('decision_trace_id', sa.UUID(), nullable=False),
    sa.Column('evidence_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['decision_trace_id'], ['decision_traces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_bundles_decision_trace_id'), 'evidence_bundles', ['decision_trace_id'], unique=False)
    op.create_index(op.f('ix_evidence_bundles_id'), 'evidence_bundles', ['id'], unique=False)
    op.create_table('journey_assessments',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('assessment_date', sa.Date(), nullable=False),
    sa.Column('assessment_type', sa.String(), nullable=False),
    sa.Column('overall_progress_rating', sa.Integer(), nullable=True),
    sa.Column('research_quality_rating', sa.Integer(), nullable=True),
    sa.Column('timeline_adherence_rating', sa.Integer(), nullable=True),
    sa.Column('strengths', sa.Text(), nullable=True),
    sa.Column('challenges', sa.Text(), nullable=True),
    sa.Column('action_items', sa.Text(), nullable=True),
    sa.Column('advisor_feedback', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_journey_assessments_user_id'), 'journey_assessments', ['user_id'], unique=False)
    op.create_table('opportunity_feed_snapshots',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('user_profile_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('timeline_context_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('total_opportunities_scored', sa.Integer(), nullable=False),
    sa.Column('feed_type', sa.String(length=50), nullable=False),
    sa.Column('subscription_tier', sa.String(length=50), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_feed_snapshots_user_date', 'opportunity_feed_snapshots', ['user_id', 'snapshot_date'], unique=False)
    op.create_index(op.f('ix_opportunity_feed_snapshots_snapshot_date'), 'opportunity_feed_snapshots', ['snapshot_date'], unique=False)
    op.create_index(op.f('ix_opportunity_feed_snapshots_user_id'), 'opportunity_feed_snapshots', ['user_id'], unique=False)
    op.create_table('baselines',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('document_artifact_id', sa.UUID(), nullable=True),
    sa.Column('program_name', sa.String(), nullable=False),
    sa.Column('institution', sa.String(), nullable=False),
    sa.Column('field_of_study', sa.String(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('expected_end_date', sa.Date(), nullable=True),
    sa.Column('total_duration_months', sa.Integer(), nullable=True),
    sa.Column('requirements_summary', sa.Text(), nullable=True),
    sa.Column('research_area', sa.Text(), nullable=True),
    sa.Column('advisor_info', sa.Text(), nullable=True),
    sa.Column('funding_status', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_artifact_id'], ['document_artifacts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_baselines_document_artifact_id'), 'baselines', ['document_artifact_id'], unique=False)
    op.create_index(op.f('ix_baselines_user_id'), 'baselines', ['user_id'], unique=False)
    op.create_table('opportunity_feed_items',
    sa.Column('feed_snapshot_id', sa.UUID(), nullable=False),
    sa.Column('opportunity_id', sa.UUID(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('overall_score', sa.Float(), nullable=False),
    sa.Column('discipline_score', sa.Float(), nullable=False),
    sa.Column('stage_score', sa.Float(), nullable=False),
    sa.Column('timeline_score', sa.Float(), nullable=False),
    sa.Column('deadline_score', sa.Float(), nullable=False),
    sa.Column('reason_tags', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('urgency_level', sa.String(length=20), nullable=False),
    sa.Column('recommended_action', sa.String(length=50), nullable=False),
    sa.Column('user_dismissed', sa.Boolean(), nullable=False),
    sa.Column('user_saved', sa.Boolean(), nullable=False),
    sa.Column('user_applied', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['feed_snapshot_id'], ['opportunity_feed_snapshots.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities_catalog.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_feed_items_snapshot_rank', 'opportunity_feed_items', ['feed_snapshot_id', 'rank'], unique=False)
    op.create_index('idx_feed_items_user_actions', 'opportunity_feed_items', ['user_saved', 'user_applied'], unique=False)
    op.create_index(op.f('ix_opportunity_feed_items_feed_snapshot_id'), 'opportunity_feed_items', ['feed_snapshot_id'], unique=False)
    op.create_index(op.f('ix_opportunity_feed_items_opportunity_id'), 'opportunity_feed_items', ['opportunity_id'], unique=False)
    op.create_table('questionnaire_drafts',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('questionnaire_version_id', sa.UUID(), nullable=False),
    sa.Column('draft_name', sa.String(), nullable=True),
    sa.Column('responses_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('completed_sections', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('progress_percentage', sa.Integer(), nullable=False),
    sa.Column('is_submitted', sa.Boolean(), nullable=False),
    sa.Column('submission_id', sa.UUID(), nullable=True),
    sa.Column('last_section_edited', sa.String(), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['questionnaire_version_id'], ['questionnaire_versions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['submission_id'], ['journey_assessments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_questionnaire_drafts_questionnaire_version_id'), 'questionnaire_drafts', ['questionnaire_version_id'], unique=False)
    op.create_index(op.f('ix_questionnaire_drafts_user_id'), 'questionnaire_drafts', ['user_id'], unique=False)
    op.create_table('draft_timelines',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('baseline_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('version_number', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['baseline_id'], ['baselines.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_draft_timelines_baseline_id'), 'draft_timelines', ['baseline_id'], unique=False)
    op.create_index(op.f('ix_draft_timelines_user_id'), 'draft_timelines', ['user_id'], unique=False)
    op.create_table('committed_timelines',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('baseline_id', sa.UUID(), nullable=True),
    sa.Column('draft_timeline_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('committed_date', sa.Date(), nullable=False),
    sa.Column('target_completion_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['baseline_id'], ['baselines.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['draft_timeline_id'], ['draft_timelines.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_committed_timelines_baseline_id'), 'committed_timelines', ['baseline_id'], unique=False)
    op.create_index(op.f('ix_committed_timelines_draft_timeline_id'), 'committed_timelines', ['draft_timeline_id'], unique=False)
    op.create_index(op.f('ix_committed_timelines_user_id'), 'committed_timelines', ['user_id'], unique=False)
    op.create_table('timeline_edit_history',
    sa.Column('draft_timeline_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('edit_type', sa.String(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('changes_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['draft_timeline_id'], ['draft_timelines.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_timeline_edit_history_draft_timeline_id'), 'timeline_edit_history', ['draft_timeline_id'], unique=False)
    op.create_index(op.f('ix_timeline_edit_history_user_id'), 'timeline_edit_history', ['user_id'], unique=False)
    op.create_table('timeline_stages',
    sa.Column('draft_timeline_id', sa.UUID(), nullable=True),
    sa.Column('committed_timeline_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('stage_order', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('duration_months', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['committed_timeline_id'], ['committed_timelines.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['draft_timeline_id'], ['draft_timelines.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_timeline_stages_committed_timeline_id'), 'timeline_stages', ['committed_timeline_id'], unique=False)
    op.create_index(op.f('ix_timeline_stages_draft_timeline_id'), 'timeline_stages', ['draft_timeline_id'], unique=False)
    op.create_table('timeline_milestones',
    sa.Column('timeline_stage_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('milestone_order', sa.Integer(), nullable=False),
    sa.Column('target_date', sa.Date(), nullable=True),
    sa.Column('actual_completion_date', sa.Date(), nullable=True),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('is_critical', sa.Boolean(), nullable=False),
    sa.Column('deliverable_type', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['timeline_stage_id'], ['timeline_stages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_timeline_milestones_timeline_stage_id'), 'timeline_milestones', ['timeline_stage_id'], unique=False)
    op.create_table('progress_events',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('milestone_id', sa.UUID(), nullable=True),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('impact_level', sa.String(), nullable=True),
    sa.Column('tags', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['milestone_id'], ['timeline_milestones.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_progress_events_milestone_id'), 'progress_events', ['milestone_id'], unique=False)
    op.create_index(op.f('ix_progress_events_user_id'), 'progress_events', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_progress_events_user_id'), table_name='progress_events')
    op.drop_index(op.f('ix_progress_events_milestone_id'), table_name='progress_events')
    op.drop_table('progress_events')
    op.drop_index(op.f('ix_timeline_milestones_timeline_stage_id'), table_name='timeline_milestones')
    op.drop_table('timeline_milestones')
    op.drop_index(op.f('ix_timeline_stages_draft_timeline_id'), table_name='timeline_stages')
    op.drop_index(op.f('ix_timeline_stages_committed_timeline_id'), table_name='timeline_stages')
    op.drop_table('timeline_stages')
    op.drop_index(op.f('ix_timeline_edit_history_user_id'), table_name='timeline_edit_history')
    op.drop_index(op.f('ix_timeline_edit_history_draft_timeline_id'), table_name='timeline_edit_history')
    op.drop_table('timeline_edit_history')
    op.drop_index(op.f('ix_committed_timelines_user_id'), table_name='committed_timelines')
    op.drop_index(op.f('ix_committed_timelines_draft_timeline_id'), table_name='committed_timelines')
    op.drop_index(op.f('ix_committed_timelines_baseline_id'), table_name='committed_timelines')
    op.drop_table('committed_timelines')
    op.drop_index(op.f('ix_draft_timelines_user_id'), table_name='draft_timelines')
    op.drop_index(op.f('ix_draft_timelines_baseline_id'), table_name='draft_timelines')
    op.drop_table('draft_timelines')
    op.drop_index(op.f('ix_questionnaire_drafts_user_id'), table_name='questionnaire_drafts')
    op.drop_index(op.f('ix_questionnaire_drafts_questionnaire_version_id'), table_name='questionnaire_drafts')
    op.drop_table('questionnaire_drafts')
    op.drop_index(op.f('ix_opportunity_feed_items_opportunity_id'), table_name='opportunity_feed_items')
    op.drop_index(op.f('ix_opportunity_feed_items_feed_snapshot_id'), table_name='opportunity_feed_items')
    op.drop_index('idx_feed_items_user_actions', table_name='opportunity_feed_items')
    op.drop_index('idx_feed_items_snapshot_rank', table_name='opportunity_feed_items')
    op.drop_table('opportunity_feed_items')
    op.drop_index(op.f('ix_baselines_user_id'), table_name='baselines')
    op.drop_index(op.f('ix_baselines_document_artifact_id'), table_name='baselines')
    op.drop_table('baselines')
    op.drop_index(op.f('ix_opportunity_feed_snapshots_user_id'), table_name='opportunity_feed_snapshots')
    op.drop_index(op.f('ix_opportunity_feed_snapshots_snapshot_date'), table_name='opportunity_feed_snapshots')
    op.drop_index('idx_feed_snapshots_user_date', table_name='opportunity_feed_snapshots')
    op.drop_table('opportunity_feed_snapshots')
    op.drop_index(op.f('ix_journey_assessments_user_id'), table_name='journey_assessments')
    op.drop_table('journey_assessments')
    op.drop_index(op.f('ix_evidence_bundles_id'), table_name='evidence_bundles')
    op.drop_index(op.f('ix_evidence_bundles_decision_trace_id'), table_name='evidence_bundles')
    op.drop_table('evidence_bundles')
    op.drop_index(op.f('ix_document_artifacts_user_id'), table_name='document_artifacts')
    op.drop_table('document_artifacts')
    op.drop_index(op.f('ix_analytics_snapshots_user_id'), table_name='analytics_snapshots')
    op.drop_index(op.f('ix_analytics_snapshots_timeline_version'), table_name='analytics_snapshots')
    op.drop_table('analytics_snapshots')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_questionnaire_versions_version_number'), table_name='questionnaire_versions')
    op.drop_table('questionnaire_versions')
    op.drop_index(op.f('ix_opportunities_catalog_opportunity_type'), table_name='opportunities_catalog')
    op.drop_index(op.f('ix_opportunities_catalog_opportunity_id'), table_name='opportunities_catalog')
    op.drop_index(op.f('ix_opportunities_catalog_is_active'), table_name='opportunities_catalog')
    op.drop_index(op.f('ix_opportunities_catalog_deadline'), table_name='opportunities_catalog')
    op.drop_index('idx_opportunities_type_active', table_name='opportunities_catalog')
    op.drop_index('idx_opportunities_deadline_active', table_name='opportunities_catalog')
    op.drop_table('opportunities_catalog')
    op.drop_index(op.f('ix_idempotency_keys_user_id'), table_name='idempotency_keys')
    op.drop_index(op.f('ix_idempotency_keys_status'), table_name='idempotency_keys')
    op.drop_index(op.f('ix_idempotency_keys_result_resource_id'), table_name='idempotency_keys')
    op.drop_index(op.f('ix_idempotency_keys_request_id'), table_name='idempotency_keys')
    op.drop_index(op.f('ix_idempotency_keys_orchestrator_name'), table_name='idempotency_keys')
    op.drop_index(op.f('ix_idempotency_keys_id'), table_name='idempotency_keys')
    op.drop_index(op.f('ix_idempotency_keys_expires_at'), table_name='idempotency_keys')
    op.drop_index(op.f('ix_idempotency_keys_created_at'), table_name='idempotency_keys')
    op.drop_table('idempotency_keys')
    op.drop_index(op.f('ix_decision_traces_request_id'), table_name='decision_traces')
    op.drop_index(op.f('ix_decision_traces_orchestrator_name'), table_name='decision_traces')
    op.drop_index(op.f('ix_decision_traces_id'), table_name='decision_traces')
    op.drop_index(op.f('ix_decision_traces_created_at'), table_name='decision_traces')
    op.drop_table('decision_traces')
    # ### end Alembic commands ###
